---

- name: Echo
  hosts: "{{class}}"
  
  tasks:
  - name: Print debug message
    debug:
      msg: "{{text}}"
      
  - name: Creates directory
    file:
      path: /tmp/polna/gradle
      state: directory
      
    - name: download sources
      get_url: url=https://services.gradle.org/distributions/{{gradle_version}} dest=/tmp/polna/gradle/{{gradle_version}}
