---

- name: Echo
  hosts: "{{class}}"
  
  tasks:
  - name: Print debug message
    debug:
      msg: "{{text}}"
  - name: Creates directory
    file:
      path: /tmp/polna/java_dns
      state: directory
