---
#here you can put i.e. seperatly hosts: back-end-server or all together hosts: "{{class}}"
- name: Echo 
  hosts: "{{class}}"

  tasks:
  - name: Print debug message
    debug:
      msg: "{{text}}"

      
